### ISSUE TITLE
CT Scan images along with contoured structure set

### ISSUE THREAD

**Issue by vinaysaini94** [nlambriICH/TMIAutomation#30]
"Providing a set of CT scan images along with this code would be of immense value for beginners, especially when applying it to patients contoured with different guidelines at other centers or institutes.

**Comment by nlambriICH** [comment]
This is a good suggestion. However, I think we may not be able to share CT and RTSTRUCT data due to confidentiality restrictions (even with anonymized data).

I will keep you posted in the next few days.

**Comment by nlambriICH** [comment]
@vinaysaini94 Unfortunately, due to privacy reasons I cannot share these data.
